// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfLx4UOQ_mozFm_Qo_PVMnphWVW6hTzY',
    appId: '1:905233487637:web:fdf8ddb0474aa7c9bebb1c',
    messagingSenderId: '905233487637',
    projectId: 'digitstitch-app',
    authDomain: 'digitstitch-app.firebaseapp.com',
    storageBucket: 'digitstitch-app.appspot.com',
    measurementId: 'G-FPQ5HMQ06D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ7tVIMqf_J19tmLq0MFvbOi9JvNC79A4',
    appId: '1:905233487637:android:41f32a2ad34aae05bebb1c',
    messagingSenderId: '905233487637',
    projectId: 'digitstitch-app',
    storageBucket: 'digitstitch-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-TIg6tpnuWh8AlnuwqkwmvRYagB_M7ug',
    appId: '1:905233487637:ios:987d78095048e8cbbebb1c',
    messagingSenderId: '905233487637',
    projectId: 'digitstitch-app',
    storageBucket: 'digitstitch-app.appspot.com',
    iosBundleId: 'com.user.digitstitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-TIg6tpnuWh8AlnuwqkwmvRYagB_M7ug',
    appId: '1:905233487637:ios:8fbf0ca94e795704bebb1c',
    messagingSenderId: '905233487637',
    projectId: 'digitstitch-app',
    storageBucket: 'digitstitch-app.appspot.com',
    iosBundleId: 'com.user.digitstitch.RunnerTests',
  );
}
